name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  # Add macOS for multi-arch testing (optional)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to v3 for potential improvements

      - name: Set up QEMU (if necessary)
        uses: docker/setup-qemu-action@v2  # Use only if building for multiple architectures
        if: runner.os != 'linux'  # Skip for Linux runners

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Updated to v2 for potential improvements

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ secrets.GIT_USER }} --password-stdin

      - name: Build and push for ${{ matrix.os }}
        uses: docker/build-push-action@v3  # Updated to v3 for potential improvements
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ secrets.GIT_USER }}/docker-container-test/my-image:${{ matrix.os }}-latest

